- name: Update and upgrade apt packages on all hosts
  hosts: all
  become: yes
  vars:
    cache_valid_time: 3600

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        cache_valid_time: "{{ cache_valid_time }}"
        upgrade: full
      when: update_apt | default(false)
