- name: Export SECRET_KEY_BASE
  ansible.builtin.shell: "echo 'export SECRET_KEY_BASE={{ rails_env_secret_key }}' >> /home/{{ app_user }}/.bashrc && source /home/{{ app_user }}/.bashrc && touch /home/{{ app_user }}/.bashrc_secret_key"
  args:
    executable: /bin/bash
    creates: "/home/{{ app_user }}/.bashrc_secret_key"
