- name: Add PostgreSQL GPG key
  ansible.builtin.apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present

- name: Add PostgreSQL APT repository
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"   
    state: present
    update_cache: true

- name: Install PostgreSQL {{ postgresql_version }} and client
  ansible.builtin.apt:
    name:
      - postgresql-{{ postgresql_version }}
      - postgresql-client-{{ postgresql_version }}
    state: present
    update_cache: yes
